/**
 * Master sports & teams configuration.
 * Single source of truth for sports used across the platform.
 *
 * hasTeams: true  → sport has team selections (NRL, AFL, etc.)
 * hasTeams: false → individual competitor sport; user follows the sport only
 *
 * The `name` field must match the Event.sport string used when creating events.
 */

export interface SportConfig {
  name: string
  hasTeams: boolean
  teams: string[]
}

export const SPORTS_CONFIG: SportConfig[] = [
  {
    name: 'AFL',
    hasTeams: true,
    teams: [
      'Adelaide Crows',
      'Brisbane Lions',
      'Carlton',
      'Collingwood',
      'Essendon',
      'Fremantle',
      'Geelong Cats',
      'Gold Coast Suns',
      'GWS Giants',
      'Hawthorn',
      'Melbourne',
      'North Melbourne',
      'Port Adelaide',
      'Richmond',
      'St Kilda',
      'Sydney Swans',
      'West Coast Eagles',
      'Western Bulldogs',
    ],
  },
  {
    name: 'Rugby League',
    hasTeams: true,
    teams: [
      'Brisbane Broncos',
      'Canberra Raiders',
      'Canterbury Bulldogs',
      'Cronulla Sharks',
      'Dolphins',
      'Gold Coast Titans',
      'Manly Sea Eagles',
      'Melbourne Storm',
      'Newcastle Knights',
      'New Zealand Warriors',
      'North Queensland Cowboys',
      'Parramatta Eels',
      'Penrith Panthers',
      'South Sydney Rabbitohs',
      'St George Illawarra Dragons',
      'Sydney Roosters',
      'Wests Tigers',
    ],
  },
  {
    name: 'EPL',
    hasTeams: true,
    teams: [
      // EPL
      'Arsenal',
      'Aston Villa',
      'Bournemouth',
      'Brentford',
      'Brighton & Hove Albion',
      'Burnley',
      'Chelsea',
      'Crystal Palace',
      'Everton',
      'Fulham',
      'Leeds United',
      'Liverpool',
      'Manchester City',
      'Manchester United',
      'Newcastle United',
      'Nottingham Forest',
      'Sheffield United',
      'Southampton',
      'Tottenham Hotspur',
      'West Ham United',
      'Wolverhampton Wanderers',
    ],
  },
  {
    name: 'Basketball',
    hasTeams: true,
    teams: [
      // NBA
        'Atlanta Hawks',
        'Boston Celtics',
        'Brooklyn Nets',
        'Charlotte Hornets',
        'Chicago Bulls',
        'Cleveland Cavaliers',
        'Dallas Mavericks',
        'Denver Nuggets',
        'Detroit Pistons',
        'Golden State Warriors',
        'Houston Rockets',
        'Indiana Pacers',
        'Los Angeles Clippers',
        'Los Angeles Lakers',
        'Memphis Grizzlies',
        'Miami Heat',
        'Milwaukee Bucks',
        'Minnesota Timberwolves',
        'New Orleans Pelicans',
        'New York Knicks',
        'Oklahoma City Thunder',
        'Orlando Magic',
        'Philadelphia 76ers',
        'Phoenix Suns',
        'Portland Trail Blazers',
        'Sacramento Kings',
        'San Antonio Spurs',
        'Toronto Raptors',
        'Utah Jazz',
        'Washington Wizards',
    ],
  },
    {
    name: 'Baseball',
    hasTeams: true,
    teams: [
      // MLB
        'Arizona Diamondbacks',
        'Atlanta Braves',
        'Baltimore Orioles',
        'Boston Red Sox',
        'Chicago Cubs',
        'Chicago White Sox',
        'Cincinnati Reds',
        'Cleveland Guardians',
        'Colorado Rockies',
        'Detroit Tigers',
        'Houston Astros',
        'Kansas City Royals',
        'Los Angeles Angels',
        'Los Angeles Dodgers',
        'Miami Marlins',
        'Milwaukee Brewers',
        'Minnesota Twins',
        'New York Mets',
        'New York Yankees',
        'Oakland Athletics',
        'Philadelphia Phillies',
        'Pittsburgh Pirates',
        'San Diego Padres',
        'San Francisco Giants',
        'Seattle Mariners',
        'St. Louis Cardinals',
        'Tampa Bay Rays',
        'Texas Rangers',
        'Toronto Blue Jays',
        'Washington Nationals',
    ],
  },
  {
    name: 'Netball',
    hasTeams: true,
    teams: [
      // Super Netball
      'Adelaide Thunderbirds',
      'Collingwood Magpies',
      'Giants Netball',
      'Melbourne Vixens',
      'NSW Swifts',
      'Queensland Firebirds',
      'Sunshine Coast Lightning',
      'West Coast Fever',
    ],
  },
  {
    name: 'Rugby Union',
    hasTeams: true,
    teams: [
      // Super Rugby Pacific
      'ACT Brumbies',
      'Auckland Blues',
      'Chiefs',
      'Crusaders',
      'Fijian Drua',
      'Force',
      'Highlanders',
      'Hurricanes',
      'Moana Pasifika',
      'NSW Waratahs',
      'Queensland Reds',
    ],
  },
  {
    name: 'Cricket',
    hasTeams: false,
    teams: [
    ],
  },
  {
    name: 'Cycling',
    hasTeams: false,
    teams: [],
  },
  {
    name: 'Golf',
    hasTeams: false,
    teams: [],
  },
  {
    name: 'Horse Racing',
    hasTeams: false,
    teams: [],
  },
  {
    name: 'Ice Hockey',
    hasTeams: true,
    teams: [
      'Anaheim Ducks',
      'Arizona Coyotes',
      'Boston Bruins',
      'Buffalo Sabres',
      'Calgary Flames',
      'Carolina Hurricanes',
      'Chicago Blackhawks',
      'Colorado Avalanche',
      'Columbus Blue Jackets',
      'Dallas Stars',
      'Detroit Red Wings',
      'Edmonton Oilers',
      'Florida Panthers',
      'Los Angeles Kings',
      'Minnesota Wild',
      'Montreal Canadiens',
      'Nashville Predators',
      'New Jersey Devils',
      'New York Islanders',
      'New York Rangers',
      'Ottawa Senators',
      'Philadelphia Flyers',
      'Pittsburgh Penguins',
      'San Jose Sharks',
      'Seattle Kraken',
      'St. Louis Blues',
      'Tampa Bay Lightning',
      'Toronto Maple Leafs',
      'Utah Mammoth',
      'Vancouver Canucks',
      'Vegas Golden Knights',
      'Washington Capitals',
      'Winnipeg Jets'
    ],
  },
  {
    name: 'Motorsport',
    hasTeams: false,
    teams: [],
  },
  {
    name: 'Commonwealth Games',
    hasTeams: false,
    teams: [],
  },
    {
    name: 'Olympic Games',
    hasTeams: false,
    teams: [],
  },
  {
    name: 'Snooker',
    hasTeams: false,
    teams: [],
  },
  {
    name: 'Tennis',
    hasTeams: false,
    teams: [],
  },
  {
    name: 'Politics',
    hasTeams: false,
    teams: [],
  },
  {
    name: 'Entertainment',
    hasTeams: false,
    teams: [],
  },
]
